# Generated by Django 4.1.7 on 2023-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogId', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=20)),
                ('madeOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
